apiVersion: v1
version: 0.1.0
appVersion: 0.1.0
name: besu-node
description: Besu nodes for a POA network
keywords:
  - ethereum
  - besu
  - hyperledger
  - private
  - enterprise
  - consensys
home: https://besu.hyperledger.org
sources:
  - https://github.com/hyperledger/besu
maintainers:
  - name: Ghislain CHENG
    email: ghislain.cheng@gmail.com
icon: http://besu.hyperledger.org/en/latest/favicon.ico

